version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - "5020:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: leave_management
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "3020:3020"
    depends_on:
      - postgres

  employee-leave:
    build: ./employee-leave
    container_name: employee-leave
    ports:
      - "8020:80"
    depends_on:
      - backend

  hr-leave:
    build: ./hr-leave
    container_name: hr-leave
    ports:
      - "8021:80"
    depends_on:
      - backend

volumes:
  pgdata:

